### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by histausse** [micronoyau/dexcaliburn#3]
Nothing happens when using 5 first class loader in the app.
Also, is it normal that the last 2 class loader use the same dex file?

**Comment by SharuMaha** [comment]
Indeed, the dex-file was hosted on a temporary filebin.

I have changed the implementation so that the apk fetches the raw dex-file from the repo instead "loadedclasses/badclass.dex". It should be working fine now.

Furthermore, the last 2 tests use the same dex file and load the same class, however, the method used is not the same.
